CREATE TABLE IF NOT EXISTS infonauts (
    name VARCHAR(50) PRIMARY KEY,
    last_login text NOT NULL
);

CREATE TABLE IF NOT EXISTS infos (
    id INTEGER PRIMARY KEY,
    creator VARCHAR(50) NULL REFERENCES infonauts(name) ON DELETE SET NULL ON UPDATE CASCADE,
    text VARCHAR (202) NOT NULL,
    creation_date text NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
    infos INTEGER NOT NULL REFERENCES infos(id) ON DELETE CASCADE ON UPDATE CASCADE,
    infonaut VARCHAR(50) NOT NULL REFERENCES infonauts(name) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (infos, infonaut)
)